swagger: "2.0"
info:
  version: "1.0.0"
  title: "App"
  description: "<p><h2 style='color:red;'>Important: Please Read!</h2></p><p><span style='color:red;'>*</span> Make sure the <b>\"Schemes\"</b> is set to <b>\"HTTP\"</b> for deimos.</p><p><span style='color:red;'>*</span> To apply header access, Click on <b><span style='color:#49cc90;'>\"Authorize\"</span></b> button. Put <b>\"Bearer\"</b> (with space) before pasting the Authentication Key</p>"

#local
# host: "localhost:8000"
# basePath: "/api/v1"

#deimos
host: "127.0.0.1:9000"
basePath: "/api/v1"

tags:
- name: "Users"
  description: "Operations about user"
- name: "Vehicles"
  description: "Operations for Vehicles"
schemes:
# - "https" #comment when running in local machine
- "http"
paths:
  # USERS ENDPOINTS #
  /register:
    post:
      tags:
      - "Users"
      summary: "Register User"
      description: ""
      operationId: "registerUser"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Register user Object"
        required: true
        schema:
          $ref: "#/definitions/userRegister"
      responses:
        200:
          description: "Success"

  /login:
    post:
      tags:
      - "Users"
      summary: "Login Registered Users"
      description: ""
      operationId: "loginUser"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "User Login user Object"
        required: true
        schema:
          $ref: "#/definitions/userLogin"
      responses:
        200:
          description: "Success"
        401:
          description: "Unauthorised"
          
  /users/details:
    get:
      tags:
      - "Users"
      summary: "Get user details using access Token"
      security: 
        - ApiKeyAuth: []
      description: ""
      operationId: "getUserDetails"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses:
        200:
          description: "Success"
          
securityDefinitions:
  ApiKeyAuth:
    type: apiKey
    in: header
    name: Authorization
    
#   api_key:
#     type: "apiKey"
#     name: "api_key"
#     in: "header"
    
definitions:
  # USER DEFINITIONS #
  userRegister:
    type: "object"
    properties:
      first_name:
        type: "string"
      middle_name:
        type: "string"
      last_name:
        type: "string"
      password:
        type: "string"
      confirm_password:
        type: "string"
      device_id:
        type: "string"
      mobile_number:
        type: "integer"
        format: "int64"
      primary_email_address:
        type: "string"
      current_address:
        type: "string"

  userLogin:
    type: "object"
    properties:
      username:
        type: "string"
      password:
        type: "string"
        
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"
